### PR TITLE
Add link for http://www.circlelinepubcrawl.co.uk/

### PR DESCRIPTION
**Pull request by brkn**
Added the link to readme.

### CODE REVIEW

**Comment by KMayne** [comment]
Please provide more info on what this PR is meant to do

**Comment by brkn** [comment]
Here is more info: https://github.com/KMayne/pub-crawl-tool/pull/40/files

**Comment by KMayne** [comment]
Sorry, this just looks like a link to your website

**Comment by brkn** [comment]
Yeah not mine, I'm not even from UK. I was thinking about making a project like pub crawling route generator. So I've searched for pub crawl in github and came across with your repo.

Since I have no idea what circle line is, I googled it and found that link. And thought it was official site for that event.

My bad, sorry for your inconvenience.

**Comment by KMayne** [comment]
No worries

**Pull request closed without merging**
